version: "3.8"

services:
  mongodb:
    image: mongo:7.0.11
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true

volumes:
  db:
